import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import MaxWidth from "@/components/MaxWidthProvider";
import Header from "./component/Header";
import Footer from "./component/Footer";
import SideBar from "./component/SideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <MaxWidth className="flex flex-col md:flex-row">
            <Header className="md:hidden" />
            <SideBar className="hidden md:flex" />
            <div className="px-4 pt-16 md:pt-28 pb-10 flex-1">{children}</div>
            <Footer className="md:hidden" />
          </MaxWidth>
        </ThemeProvider>
      </body>
    </html>
  );
}
